version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: 
      context: ./apps/backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/usr/src/app
    depends_on:
      - mysql

  frontend:
    build: 
      context: ./apps/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
    depends_on:
      - backend

volumes:
  mysql-data:
